services:
  mongo:
    image: mongo:latest
    container_name: "llm_engineering_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "llm_engineering"
      MONGO_INITDB_ROOT_PASSWORD: "llm_engineering"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "llm_engineering_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always

  ollama:
    image: ollama/ollama:latest  # Ollama image
    container_name: "llm_engineering_ollama"
    ports:
      - 11400:11400  # Ollama API port
    networks:
      - local
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure you have a Dockerfile for the Gradio app
    container_name: "llm_engineering_app"
    ports:
      - 7860:7860  # Gradio app port
    depends_on:
      - mongo
      - qdrant
      - ollama
    networks:
      - local
    restart: always

volumes:
  mongo_data:
  qdrant_data:

networks:
  local:
    driver: bridge
